In [1]:
# HPC 4 : 4. Write a CUDA Program for:  
#    1. Addition of two large vectors  
#    2. Matrix Multiplication using CUDA C

In [2]:
import numpy as np
import time

# Function to add two large vectors
def vecAdd():
    n = 10000000  # 10 million elements

    # Host input vectors (created using NumPy)
    h_a = np.arange(n, dtype=np.float64)
    h_b = np.arange(n, dtype=np.float64)

    # Start the timer
    start = time.time()

    # Perform vector addition
    h_c = h_a + h_b

    # End the timer
    end = time.time()

    print("First 10 elements of result vector:", h_c[:10])
    print("Time taken for vector addition on CPU:", end - start, "seconds")

# Function to multiply two N x N matrices
def matMul():
    N = 1024  # 1024 x 1024 matrices

    # Host matrices (created using NumPy)
    h_a = np.random.rand(N, N).astype(np.float64)
    h_b = np.random.rand(N, N).astype(np.float64)

    # Start the timer
    start = time.time()

    # Perform matrix multiplication
    h_c = np.matmul(h_a, h_b)

    # End the timer
    end = time.time()

    print("First 5x5 block of result matrix:\n", h_c[:5, :5])
    print("Time taken for matrix multiplication on CPU:", end - start, "seconds")

def main():
    print("Add two large vectors:")
    vecAdd()

    print("\nMultiply two N x N matrices:")
    matMul()

if __name__ == "__main__":
    main()


Add two large vectors:
First 10 elements of result vector: [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
Time taken for vector addition on CPU: 0.045630455017089844 seconds

Multiply two N x N matrices:
First 5x5 block of result matrix:
 [[254.50149338 257.76384787 254.54299435 243.39258865 247.30732922]
 [261.44887198 260.85631613 260.63301026 253.97382039 245.575424  ]
 [263.8639572  266.23277841 265.77497254 259.37889933 254.02905577]
 [260.19950995 268.22608847 260.56738581 251.64519372 252.16756179]
 [254.67306211 258.52343275 253.17009897 246.60694712 239.39427483]]
Time taken for matrix multiplication on CPU: 0.047255754470825195 seconds
